# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./commitmessagehistorymodelinterface.h \
    ./commitmessagehistoryitemmodel.h \
    ./commitpad.h \
    ./commitsyntaxhighlighter.h \
    ./settingsdialog.h \
    ./titlebar.h
SOURCES += ./commitmessagehistoryitemmodel.cpp \
    ./commitpad.cpp \
    ./commitsyntaxhighlighter.cpp \
    ./main.cpp \
    ./settingsdialog.cpp \
    ./titlebar.cpp
FORMS += ./commitpad.ui \
    ./settingsdialog.ui
RESOURCES += commitpad.qrc
